# Generated by Django 3.2.3 on 2021-06-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='التاريخ')),
                ('is_finished', models.BooleanField(default=False, verbose_name='التأكيد')),
                ('phone', models.PositiveIntegerField(verbose_name='الهاتف')),
                ('adderess', models.CharField(max_length=250, verbose_name='العنوان')),
                ('gover', models.CharField(choices=[('b', 'بغداد'), ('m', 'محافظات')], max_length=1, verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعر')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='العدد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='الكتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='الطلب')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(through='orders.OrderDetails', to='books.Book', verbose_name=''),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الطلب'),
        ),
    ]
