# Generated by Django 3.2.3 on 2021-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210609_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السعر'),
        ),
    ]
