# Generated by Django 3.2.3 on 2021-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='القائل')),
                ('quotation', models.CharField(max_length=250, verbose_name='الاقتباس أو القول')),
                ('image', models.ImageField(upload_to='Quotes/%Y/%m-%d', verbose_name='صورة الشخص')),
                ('pubish', models.BooleanField(verbose_name='ينشر')),
            ],
            options={
                'verbose_name': 'اقتباس',
                'verbose_name_plural': 'أقتباسات',
            },
        ),
        migrations.CreateModel(
            name='slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=50, verbose_name='اسم السلايد')),
                ('img', models.ImageField(upload_to='slides/%Y/%m-%d', verbose_name='الصورة')),
                ('show', models.BooleanField(verbose_name='يظهر')),
            ],
            options={
                'verbose_name': 'السلايد',
                'verbose_name_plural': 'السلايدات',
            },
        ),
        migrations.CreateModel(
            name='Comming_soon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50, verbose_name='اسم الكتاب')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('cover_book', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='صورة ')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعر')),
                ('year_publish', models.DateField(blank=True, null=True, verbose_name='سنة النشر')),
                ('description_book', models.TextField(blank=True, null=True, verbose_name='مختصر عن الكتاب')),
                ('publish', models.BooleanField(default=False, verbose_name='يتم نشره')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
                ('Categories', models.ManyToManyField(to='books.Categories', verbose_name='الفئة')),
                ('Publishers', models.ManyToManyField(to='books.Publishers', verbose_name='الناشر')),
                ('auther', models.ManyToManyField(to='books.Authors', verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'كتاب مترقب',
                'verbose_name_plural': 'كتب مترقبة',
            },
        ),
    ]
