# Generated by Django 3.2.3 on 2021-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='categories',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='publishers',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='stores',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
    ]
