# Generated by Django 3.2.3 on 2021-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_showinslideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Stores',
            field=models.ManyToManyField(related_name='store_book', to='books.Stores', verbose_name='المتجر'),
        ),
    ]
