# Generated by Django 3.2.3 on 2021-05-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Stores',
            new_name='stores',
        ),
    ]
