# Generated by Django 3.2.3 on 2021-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_stores_book_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=20, null=True),
        ),
    ]
