# Generated by Django 3.2.3 on 2021-05-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_stores_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='slug',
        ),
    ]
