# Generated by Django 3.2.3 on 2021-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_stores_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='slugy',
            field=models.SlugField(allow_unicode=True, max_length=20, null=True),
        ),
    ]
