# Generated by Django 3.2.3 on 2021-05-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_stores_slugy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='dirctors_store',
        ),
    ]
