# Generated by Django 3.2.3 on 2021-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_stores_dirctors_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='slugy',
            new_name='slug',
        ),
    ]
