# Generated by Django 3.2.3 on 2021-05-29 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_rename_slugy_stores_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='slug',
        ),
        migrations.AddField(
            model_name='stores',
            name='dirctors_store',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='المدراء'),
        ),
    ]
