# Generated by Django 3.2.3 on 2021-06-05 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='السعر')),
                ('is_send', models.BooleanField(default=False, verbose_name='تم التأكيد')),
                ('is_closed', models.BooleanField(default=False, help_text='في حال تم ارسال الطلبية لصاحبها ', verbose_name='إغلاق')),
                ('user_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الطلب')),
            ],
            options={
                'verbose_name': 'الطلبية',
                'verbose_name_plural': 'الطلبيات',
            },
        ),
        migrations.CreateModel(
            name='Factor_Detailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.DecimalField(decimal_places=0, default=1, max_digits=7, verbose_name='العدد')),
                ('detail_price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='مجموع السعر')),
                ('book_id', models.ManyToManyField(to='books.Book', verbose_name='الكتاب')),
                ('factor_id', models.ManyToManyField(to='factors.Factor', verbose_name='الطلبية')),
            ],
        ),
    ]
