# Generated by Django 3.2.3 on 2021-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor_detailes',
            options={'verbose_name': 'تفاصيل الطلبية', 'verbose_name_plural': 'تفاصيل الطلبيات '},
        ),
    ]
