# Generated by Django 3.2.3 on 2021-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_alter_factor_detailes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor_detailes',
            name='factor_id',
        ),
    ]
