# Generated by Django 3.2.3 on 2021-06-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_remove_factor_detailes_factor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor_detailes',
            name='factor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factors.factor', verbose_name='الطلبية'),
        ),
    ]
