# Generated by Django 3.2.3 on 2021-06-07 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0004_factor_detailes_factor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='factor',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الطلب'),
        ),
    ]
