# Generated by Django 3.2.3 on 2021-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('factors', '0005_auto_20210607_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor_detailes',
            name='book_id',
            field=models.ManyToManyField(related_name='books', to='books.Book', verbose_name='الكتاب'),
        ),
    ]
