# Generated by Django 3.2.3 on 2021-06-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0006_alter_factor_detailes_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor_detailes',
            name='factor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='factors.factor', verbose_name='الطلبية'),
        ),
    ]
