# Generated by Django 3.2.3 on 2021-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السعر'),
        ),
    ]
