# Generated by Django 3.2.3 on 2021-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='account/avatar/', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
